# Generated by Django 4.2.1 on 2023-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=30)),
                ('rut', models.IntegerField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField(max_length=9)),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('vivienda', models.IntegerField(choices=[(1, 'Casa con patio Grande'), (2, 'Casa con Patio Pequeño'), (3, 'Casa sin patio'), (4, 'Departamento')])),
            ],
        ),
    ]
