# Generated by Django 4.2.1 on 2023-05-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0003_listaperros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listaPerros',
            new_name='Lista_perros',
        ),
    ]
