# Generated by Django 4.2.1 on 2023-05-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0006_alter_lista_perros_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_perros',
            name='id',
        ),
        migrations.AddField(
            model_name='lista_perros',
            name='codigo',
            field=models.IntegerField(default=897, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
