# Generated by Django 4.2.1 on 2023-05-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0007_remove_lista_perros_id_lista_perros_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='vivienda',
            field=models.CharField(choices=[(1, 'Casa con patio Grande'), (2, 'Casa con Patio Pequeño'), (3, 'Casa sin patio'), (4, 'Departamento')], max_length=1000),
        ),
    ]
