# Generated by Django 4.2.1 on 2023-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0009_lista_perros_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_perros',
            name='estado',
            field=models.CharField(choices=[(1, 'Rescatado'), (2, 'Disponible'), (3, 'Adoptado')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='lista_perros',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_perros'),
        ),
    ]
