# Generated by Django 4.2.1 on 2023-06-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0010_alter_lista_perros_estado_alter_lista_perros_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_perros',
            name='estado',
            field=models.CharField(choices=[('rescatado', 'Rescatado'), ('disponible', 'Disponible'), ('adoptado', 'Adoptado')], max_length=1000),
        ),
    ]
