# Generated by Django 4.2.1 on 2023-06-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0011_alter_lista_perros_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_perros',
            name='estado',
            field=models.CharField(choices=[('rescatado', 'Rescatado'), ('disponible', 'Disponible'), ('adoptado', 'Adoptado'), ('revision', 'revision psiquiatrica')], max_length=1000),
        ),
    ]
