# Generated by Django 4.2.1 on 2023-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0012_alter_lista_perros_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='vivienda',
            field=models.CharField(choices=[('grande', 'Casa con patio Grande'), ('pequeño', 'Casa con Patio Pequeño'), ('notiene', 'Casa sin patio'), ('notiene1', 'Departamento')], max_length=1000),
        ),
    ]
